name: Build RPM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      release:
        required: true
        type: string
      executor:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    outputs:
      rpm_name: ${{ steps.get_rpm.outputs.rpm_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Build with build.sh
        working-directory: src/xbatd
        run: ./build.sh ${{ inputs.version }} --release ${{ inputs.release }} --distro el10 --executor ${{ inputs.executor }}

      - name: Find RPM
        id: get_rpm
        working-directory: src/xbatd
        run: |
          RPM_NAME=$(ls xbatd-${{ inputs.version }}-${{ inputs.release }}.el10*.rpm)
          echo "Found RPM: $RPM_NAME"
          echo "rpm_name=$RPM_NAME" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: rpm-el10
          path: src/xbatd/xbatd-${{ inputs.version }}-${{ inputs.release }}.el10*.rpm
